config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'works/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "groups#index"
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :destroy] do
    resources :works, only: [:index, :new, :create, :edit, :destroy, :update,:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups, dependent: :destroy
  has_many :works, dependent: :destroy

  validates :group_name,  presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_groups
  has_many :groups,  through: :user_groups

  validates :name, presence:  true
  validates :email, uniqueness: true
end

app/models/user_group.rb
class UserGroup < ApplicationRecord

  belongs_to :user
  belongs_to :group
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :group, optional: true

  with_options presence:  true do
    validates :contents
    validates :work_name
    validates :progress
  end

  validates :progress, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to:100 }
  validate :deadline_check

  def deadline_check
    errors.add(:deadline, "is already passed or is blank.") if deadline.blank? || deadline < Date.today
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth if Rails.env.production?
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end
  def index
    @group = Group.where(user_id: current_user.id)
    @groups = UserGroup.where(user_id: current_user.id)
  end
  
  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to root_path
  end


  private
  
  def group_params
    params.require(:group).permit(:group_name, user_ids: []).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :work_new, only:  [:index,:new]
  before_action :find_params, only: [:index, :create, :update]
  def index
    @works = @group.works.where.not(progress: 100).order(deadline: "ASC")
  end

  def new
  end

  def create
    @work = @group.works.new(work_params)
    if @work.save
      redirect_to group_works_path(@group)
    else
      render :new
    end
  end

  def destroy
    work = Work.find(params[:id])
    if work.destroy
      redirect_to root_path
    else
      render root_path
    end
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    work = Work.find(params[:id])
    if work.update(work_params)
      redirect_to group_works_path(@group)
    else
      render :edit
    end
  end

  def show
    @work = Work.find(params[:id])
  end

  private

  def work_new
    @work = Work.new
  end
  def find_params
    @group = Group.find(params[:group_id])
  end
  def work_params
    params.require(:work).permit(:contents, :deadline, :work_name, :progress).merge(group_id: params[:group_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/groups/_main_screen.html.erb
<% if @groups.blank?  %>
  <div class="main-screen-notice">
    <%= link_to "グループを登録してください", new_group_path %>
  </div>
  <% else %>
  <div class="main-screen-notice">
    左からグループを選択してください！
  </div>
<% end %>

app/views/groups/_menu_bar.html.erb
<div class="menu_bar">
  <div class="logo">
    <%= link_to image_tag("logo.png", class:"icon"), "/" %>
  </div>
  <div class="menu">
    <ul class="item">
      <li class="items"><%= link_to "グループを作成する", new_group_path %></li>
      <li class="items"><%= link_to "ユーザー情報の編集", edit_user_path(current_user) %></li>
      <li class="items"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</div>

app/views/groups/_side_bar.html.erb
<div class="current_user">
  <%= current_user.name %> さん
</div> 

<div class="group-list-title">
所属グループ一覧
</div>
  <% current_user.groups.each do |group| %>
    <div class="work-name">
      <%= link_to group.group_name, group_works_path(group) %>
    </div>
  <% end %>

app/views/groups/index.html.erb
<div class="menu_bar">
  <%= render "menu_bar" %>
</div>
<div class="wrapper">
  <div class="side_bar">
    <%= render "side_bar" %>
  </div>
  <div class="main_screen">
    <%= render "main_screen" %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="contents">
  <div class="container">
    <h3>新規グループ作成</h3>

    <div class="group-sumit-form">
      <%= form_with model: @group, local: true do |f| %>

        <div class="field">
          <%= f.label :group_name %>
          <%= f.text_field :group_name, pllaceholder: 'Please input group name' %>
        </div>
        <div class="field">
          <table border="0" >
            <%= collection_check_boxes :group, :user_ids, User.where.not(id:current_user.id), :id, :name, include_hidden: false do |user|%>
              <tr>
                <div class="user-name-select">
                <td><%= user.label { user.check_box + user.text }%></td>
                </div>
              </tr>
            <%end%>
          </table>
        </div>
        <input name="group[user_ids][]" type="hidden" value=<%= current_user.id %>>
        <div class="btn">
          <%= f.submit "Create Group",class: "btn"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkControl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
<h3>アカウントの編集</h3>

  <div class="user-info-edit">
    <%= form_with model: current_user, local: true do |f| %>
      <div class="field">
        <%= f.label :name %><br/>
        <%= f.text_field :name, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :email %><br/>
        <%= f.email_field :email %>
      </div>

      <div class="btn">
        <%= f.submit "Account information Update", class: 'btn' %>
      </div>

    <% end %>
  </div>
</div>

app/views/works/_menu_bar.html.erb
<div class="menu_bar">
  <div class="logo">
    <h1 class="title">Work Control</h1>
  </div>
  <div class="menu">
    <ul class="item">
      <li class="items">仕事一覧</li>
      
      <li class="items">仕事を提案する</li>
      <li class="items"><%= link_to "グループを作成する", new_group_path %></li>
      <li class="items"><%= link_to "ユーザー情報の編集", edit_user_path(current_user) %></li>
      <li class="items"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</div>

app/views/works/_side_bar.html.erb
<div class="current_user">
  <%= current_user.name %> さん
</div> 

<%# 以下、所属するグループのリンクが並ぶように %>
<div class="group-list-title">
所属グループ一覧
</div>
  <% current_user.groups.each do |group| %>
    <a href="#"><%= group.group_name %></a>
  <% end %>

app/views/works/edit.html.erb
<div class="container">
  <h3>仕事編集画面</h3>
  <div class="works-edit-form">
    <%= form_with model: @work, url: :group_work, local: true do |f| %>
      
      <div class="field">
        <%= f.label :work_name %><br/>
        <%= f.text_field :work_name, placeholder: 'Please input work name' %>
      </div>

      <div class="field">
        <%= f.label :deadline %><br/>
        <%= f.date_field :deadline %>
      </div>

      <div class="field">
        <%= f.label :contents %><br/>
        <%= f.text_area :contents %>
      </div>
      
      <div class="field">
        <%= f.label :progress %></br>
        <%= f.number_field :progress %>
      </div>

      <div class="btn">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/works/index.html.erb
<div class="menu_bar">
  <%= render "groups/menu_bar" %>
</div>
<div class="wrapper">
  <div class="side_bar">
    <%= render "groups/side_bar" %>
  </div>
  <div class="works-main-screen">
    <div class="group_name">
      現在は  <%= @group.group_name %>  にいます。
      <div class="menu-btn">
        <%= link_to "グループを解散する", group_path(@group), method: :delete %>
        <%= link_to "仕事を登録する", new_group_work_path(params[:group_id]) %>
      </div>
    </div>
    <div class="work-table" >
      <table border="0" width="1000" >
        <tr>
          <th>仕事名</th>
          <th>期日</th>
          <th>仕事内容</th>
          <th>進捗状況</th>
        </tr><br/>
        <% @works.each do |work|%>
          <div class="work">
            <tr>
              <td><%= link_to work.work_name, group_work_path(@group, work.id) %></td>
              <td><%= work.deadline%></td>
              <td><%= work.contents%></td>
              <td><%= work.progress%>%</td>
              <td><%= link_to "編集", edit_group_work_path(@group, work.id), method: :get %></td>
              <td><%= link_to "削除", group_work_path(@group, work.id), method: :delete %></td>
            </tr>
          </div>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/works/new.html.erb
<div class="container">
  <h3>仕事登録画面</h3>

  <%= form_with model: @work, url: group_works_path, local: true do |f| %>

    <div class="field">
      <%= f.label :work_name %><br/>
      <%= f.text_field :work_name, placeholder: 'Please input work name' %>
    </div>

    <div class="field">
      <%= f.label :deadline %><br/>
      <%= f.date_field :deadline %>
    </div>
    
    <div class="field">
      <%= f.label :contents %><br/>
      <%= f.text_area :contents %>
    </div>

    <div class="field">
      <%= f.label :progress %></br>
      <%= f.number_field :progress %>
    </div>
    
    <div class="btn">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/works/show.html.erb
<div class="menu_bar">
  <%= render "groups/menu_bar" %>
</div>
<div class="wrapper">
  <div class="side_bar">
    <%= render "groups/side_bar" %>
  </div>

  <div class="works-contents">
    <div class="works-contents-screen">
      仕事名:<%= @work.work_name %></br>
      期日:<%= @work.deadline %></br>
      進捗状況:<%= link_to @work.progress, edit_group_work_path(params[:id]) %>%</br>
      仕事内容:
      <%= @work.contents %></br>
    </div>
    <div class="btn">
      <%= link_to "編集する", edit_group_work_path(@work.id) %>
      <%= link_to "削除する", group_work_path(@work.id), method: :delete %> 
    </div>
  </div>
</div>